apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moglix
  template:
    metadata:
      labels:
        app: moglix
    spec:
      containers:
      - name: my-app
        image: asia-south1-docker.pkg.dev/searce-playground-v1/testing/demo-angular:tagversion
        imagePullPolicy: Always
        ports:
        - containerPort: 4200
        
---

apiVersion: v1
kind: Service
metadata:
  name: my-moglix-service
  labels:
    app: moglix
  annotations:
    cloud.google.com/load-balancer-type: "HTTP(S)"  
spec:
  selector:
    app: moglix
  ports:
  - name: http
    port: 80
    protocol: TCP
  type: LoadBalancer

